"""Incremental JSON parser for streaming TipTap document generation."""

import json
import logging
from typing import List, Dict, Any, Set

logger = logging.getLogger(__name__)


class TipTapStreamingParser:
    """
    Incrementally parse TipTap JSON and yield complete nodes in real-time.
    
    This parser uses a robust depth-tracking approach to extract complete content nodes
    (paragraphs, headings, etc.) as they are generated by the LLM, enabling true 
    real-time streaming without waiting for complete JSON.
    
    Unlike heuristic-based approaches, this parser tracks ALL objects at content depth
    and validates them after parsing, ensuring no nodes are missed.
    """
    
    def __init__(self):
        """Initialize the streaming parser."""
        self.buffer = ""
        self.depth = 0
        self.in_string = False
        self.escape_next = False
        
        # Track candidate objects at various depths
        self.candidates = []  # List of (start_pos, start_depth, bracket_stack)
        
        # Deduplication: track already-sent nodes
        self.parsed_node_hashes: Set[int] = set()
        
        # Statistics
        self.total_parsed = 0
        self.total_streamed = 0
        
        # Auto-repair tracking
        self.last_structural_char = None  # '}', ']', or '"' (end of string)
        self.last_structural_pos = -1
        self.commas_inserted = 0
        
    def feed(self, chunk: str) -> List[Dict[str, Any]]:
        """
        Feed a chunk of JSON text and return any complete streamable nodes.
        
        This method uses a robust approach:
        1. Track ALL opening braces and their depth
        2. When a closing brace completes an object, try to parse it
        3. If it's a valid streamable node, send it (once, via dedup)
        4. No heuristics, no guessing, no missed nodes
        
        Args:
            chunk: String chunk from LLM stream
            
        Returns:
            List of complete TipTap nodes ready to stream to client
        """
        if not chunk:
            return []
        
        self.buffer += chunk
        complete_nodes = []
        
        # Scan through buffer character by character
        i = 0
        while i < len(self.buffer):
            char = self.buffer[i]
            
            # Handle escape sequences in strings
            if self.escape_next:
                self.escape_next = False
                i += 1
                continue
            
            if char == '\\':
                self.escape_next = True
                i += 1
                continue
            
            # Track string boundaries (don't parse structure inside strings)
            if char == '"':
                if not self.in_string:
                    # Starting a string - check for missing comma before it
                    self._check_and_repair_missing_comma(i, '"')
                else:
                    # Ending a string - mark as structural
                    self.last_structural_char = '"'
                    self.last_structural_pos = i
                
                self.in_string = not self.in_string
                i += 1
                continue
            
            # Only track JSON structure outside of strings
            if not self.in_string:
                if char == '{':
                    # Opening brace - this might start a content node
                    # Track it as a candidate regardless of position
                    self.candidates.append({
                        'start': i,
                        'depth': self.depth,
                    })
                    self.depth += 1
                    i += 1
                    continue
                    
                elif char == '}':
                    self.depth -= 1
                    
                    # Check if any candidate object just completed
                    # (closing brace returns to candidate's starting depth)
                    completed_candidates = [
                        c for c in self.candidates 
                        if c['depth'] == self.depth
                    ]
                    
                    for candidate in completed_candidates:
                        # Extract the complete JSON object
                        obj_json = self.buffer[candidate['start']:i+1]
                        
                        # Try to parse it
                        try:
                            obj = json.loads(obj_json.strip())
                            self.total_parsed += 1
                            
                            # Check if this is a streamable content node
                            if self._is_streamable_node(obj):
                                # Deduplicate: only send each unique node once
                                node_hash = hash(json.dumps(obj, sort_keys=True))
                                
                                if node_hash not in self.parsed_node_hashes:
                                    self.parsed_node_hashes.add(node_hash)
                                    complete_nodes.append(obj)
                                    self.total_streamed += 1
                                    
                                    logger.debug(
                                        f"✅ Streamed node #{self.total_streamed}: "
                                        f"{obj.get('type')} (depth {candidate['depth']})"
                                    )
                                else:
                                    logger.debug(
                                        f"⏭️  Skipped duplicate: {obj.get('type')}"
                                    )
                        
                        except json.JSONDecodeError as e:
                            # Not valid JSON yet (incomplete nested structure)
                            # This is normal during streaming - just skip
                            logger.debug(
                                f"Incomplete object at depth {candidate['depth']}: "
                                f"{str(e)[:50]}"
                            )
                        except Exception as e:
                            # Unexpected error - log but don't crash
                            logger.warning(
                                f"Unexpected parser error: {e}", exc_info=False
                            )
                        
                        # Remove this candidate (whether parsed or not)
                        self.candidates.remove(candidate)
                    
                    i += 1
                    continue
                
                elif char == '[':
                    # Opening array bracket
                    self.depth += 1
                    self.last_structural_char = None
                    self.last_structural_pos = -1
                    i += 1
                    continue
                    
                elif char == ']':
                    # Closing array bracket
                    self.depth -= 1
                    self.last_structural_char = ']'
                    self.last_structural_pos = i
                    i += 1
                    continue
                
                elif char == ',':
                    # Comma found - reset structural tracking
                    self.last_structural_char = None
                    self.last_structural_pos = -1
                    i += 1
                    continue
            
            i += 1
        
        # Aggressive buffer management to prevent memory bloat
        # Keep only the most recent content for ongoing parsing
        if len(self.buffer) > 20000:
            # Keep last 10000 chars, but also clean up old candidates
            chars_to_trim = len(self.buffer) - 10000
            self.buffer = self.buffer[chars_to_trim:]
            
            # Adjust candidate positions
            self.candidates = [
                {
                    'start': max(0, c['start'] - chars_to_trim),
                    'depth': c['depth']
                }
                for c in self.candidates
                if c['start'] >= chars_to_trim  # Remove candidates before trim point
            ]
            
            logger.debug(
                f"🗑️  Trimmed buffer by {chars_to_trim} chars. "
                f"Remaining: {len(self.buffer)} chars, {len(self.candidates)} candidates"
            )
        
        if complete_nodes:
            logger.info(
                f"📦 Batch: {len(complete_nodes)} nodes streamed "
                f"(total: {self.total_streamed}, parsed: {self.total_parsed})"
            )
        
        return complete_nodes
    
    def _is_streamable_node(self, obj: Dict[str, Any]) -> bool:
        """
        Determine if a parsed object is a streamable content node.
        
        We stream content-level blocks (paragraphs, headings, lists, etc.)
        but NOT structural containers (doc, page) or inline text nodes.
        
        Args:
            obj: Parsed JSON object
            
        Returns:
            True if this node should be streamed to frontend
        """
        if not isinstance(obj, dict):
            return False
        
        node_type = obj.get("type", "")
        
        # Stream these content block types
        streamable_types = {
            "heading",
            "paragraph",
            "bulletList",
            "orderedList",
            "listItem",
            "blockquote",
            "codeBlock",
            "table",
            "tableRow",
            "tableCell",
            "horizontalRule",
            "image",
            "hardBreak",
        }
        
        # Do NOT stream these (structural/container or inline)
        non_streamable = {
            "doc",       # Root container
            "page",      # Page container
            "pageBreak", # Structural only
            "text",      # Inline text (streamed as part of parent)
        }
        
        is_streamable = node_type in streamable_types
        
        if is_streamable:
            logger.debug(f"✓ Streamable: {node_type}")
        elif node_type in non_streamable:
            logger.debug(f"✗ Structural: {node_type} (not streaming)")
        
        return is_streamable
    
    def _check_and_repair_missing_comma(self, pos: int, next_char: str) -> None:
        """
        Check if a comma is missing before a structural element and auto-repair.
        
        This detects patterns like:
        - } "key": (missing comma after })
        - ] { (missing comma after ])
        - "value" "key": (missing comma between strings)
        """
        if self.last_structural_char not in ['}', ']', '"']:
            return
        
        if self.last_structural_pos < 0:
            return
        
        # Check if there's a comma between last structural char and this one
        between = self.buffer[self.last_structural_pos + 1:pos]
        between_stripped = between.strip()
        
        # If there's no comma and it's mostly whitespace, insert one
        if ',' not in between_stripped and (not between_stripped or between_stripped.isspace()):
            # Check if this looks like it needs a comma
            needs_comma = False
            
            if next_char == '"':
                # Check if this is a property name (followed by ":")
                lookahead = pos + 1
                while lookahead < len(self.buffer) and self.buffer[lookahead].isspace():
                    lookahead += 1
                if lookahead < len(self.buffer) and self.buffer[lookahead] == ':':
                    needs_comma = True
            elif next_char in ['{', '[']:
                # Definitely needs comma before object/array
                needs_comma = True
            
            if needs_comma:
                # Insert comma after the last structural character
                insert_pos = self.last_structural_pos + 1
                # Find first non-whitespace position after structural char
                while insert_pos < len(self.buffer) and self.buffer[insert_pos].isspace():
                    insert_pos += 1
                
                # Insert comma
                self.buffer = self.buffer[:insert_pos] + ',' + self.buffer[insert_pos:]
                self.commas_inserted += 1
                
                # Adjust position since we inserted a character
                # Note: This is tricky - we need to adjust i in the calling loop
                # For now, we'll log and let the validator catch it
                logger.debug(
                    f"🔧 Auto-repaired missing comma at position {insert_pos} "
                    f"(after {self.last_structural_char} before {next_char})"
                )
    
    def reset(self):
        """Reset parser state for new document generation."""
        self.buffer = ""
        self.depth = 0
        self.in_string = False
        self.escape_next = False
        self.candidates = []
        self.parsed_node_hashes = set()
        self.total_parsed = 0
        self.total_streamed = 0
        self.last_structural_char = None
        self.last_structural_pos = -1
        self.commas_inserted = 0
        logger.info("🔄 Parser reset for new document")
    
    def get_stats(self) -> Dict[str, Any]:
        """Get parser statistics for debugging."""
        return {
            "total_parsed": self.total_parsed,
            "total_streamed": self.total_streamed,
            "buffer_size": len(self.buffer),
            "active_candidates": len(self.candidates),
            "dedupe_cache_size": len(self.parsed_node_hashes),
            "commas_inserted": self.commas_inserted,
        }
